### ISSUE TITLE
float precision

### ISSUE THREAD

**Issue by Phunkafizer** [hyperrealm/libconfig#58] opened 2016-02-10 13:08 UTC
```
#include <iostream>
#include <libconfig.h++>

using namespace std;
using namespace libconfig;

int main (void) {
    Config cfg;

    cfg.getRoot().add("avalue", Setting::TypeFloat);
    cfg.getRoot()["avalue"] = (double) 4.1837;

    cfg.writeFile("test.cfg");

    return 0;
}
```

results in:

`avalue = 4.18;`

**Comment by hyperrealm** [comment] 2017-10-16 06:06
Duplicate of #81 ?

**Comment by hyperrealm** [comment] 2017-10-17 04:13
The default float precision was 2. I changed it to 6 in d87d75f, but of course it's configurable via the API. So not really a bug, but a bad choice for a default.

**Closed by hyperrealm** 2017-10-17 04:13 UTC
Labels: bug
