### ISSUE TITLE
can i get config file path from a libconfig::Config object?

### ISSUE THREAD

**Issue by nickhuangxinyu** [hyperrealm/libconfig#192] opened 2021-05-01 07:46 UTC
i know the normal usage is:

```
libconfig::Config cfg;
cfg.readFile(path);
```
my question is:

Can i get the path from cfg object?

like:   cfg.getpath() to get filepath?

**Comment by hyperrealm** [comment] 2021-06-19 23:17
libconfig::Setting has methods getSourceFile() and getSourceLine() that give you this information. So call getSourceFile() on the root setting to get the toplevel filename. There can be multiple files if include statements are used, so each setting potentially has a unique filename/line.

**Comment by hyperrealm** [comment] 2021-06-19 23:19
Closing as working as intended.

**Closed** 2021-06-20 00:15 UTC
