### ISSUE TITLE
Save Comment for config_write_file

### ISSUE THREAD

**Issue by or75** [hyperrealm/libconfig#88] opened 2017-11-13 09:18 UTC
config before:
```
# 1
// 2
/* 3 */

Aplication : 
{
    Enable = false; // easy
};
```
config after config_write_file (comments are not saved):
```
Aplication : 
{
    Enable = false;
};
```
if use CONFIG_OPTION_SAVE_ANOTHER_LINES, config_write_file:
```
# 1
// 2
/* 3 */

Aplication : 
{
    Enable = false; // easy
};
```

example option:
1) CONFIG_OPTION_SAVE_ANOTHER_LINES (comments and etc)
2) CONFIG_OPTION_SAVE_USE_TAB (use a tab delimiter instead of a space) (config_set_tab_width use space delimiter)

**Comment by hyperrealm** [comment] 2017-11-13 19:24
You can already specify tab characters for output by setting the tab width to 0. The rest is a dupe of issue #35

**Closed** 2017-11-13 21:06 UTC
