### ISSUE TITLE
undefined reference to 'config_setting_lookup'

### ISSUE THREAD

**Issue by luongnv89** [hyperrealm/libconfig#64] opened 2016-05-10 11:01 UTC
- **Environment**: Ubuntu Server 14.04, make 3.81
- **libconfig version**: 1.5

(I could not install the latest version of libconfig (I got same problem here #53 ). I am using version 1.5 which has been installed by command line `sudo apt-get install libconfig-dev`)
- **Problem**:  `undefined reference to 'config_setting_lookup'`
- I have modified the configuration file `examples/example.cfg` and `example/example1.c` to have many authors for a book:

`examples/example.cfg`

```
books = ( { title  = "Treasure Island";
              author = ["Robert Louis Stevenson","Nobody"];
              price  = 29.99;
              qty    = 5; },
            { title  = "Snow Crash";
              author = ["Neal Stephenson"];
              price  = 9.99;
              qty    = 8; }
          );
```

`example/example1.c`

```
config_setting_t *authors = config_setting_lookup(book, "author", &author);
      if(!(config_setting_lookup_string(book, "title", &title)
           && author
           && config_setting_lookup_float(book, "price", &price)
           && config_setting_lookup_int(book, "qty", &qty)))
        continue;
```

P/S: In the source code (version 1.5 I have grabbed here: https://launchpad.net/ubuntu/+source/libconfig/1.5-0.2 ), I could see there is `config_setting_lookup` function: `libconfig.h:270` and `libconfig.c:1189`

**Comment by hyperrealm** [comment] 2017-10-17 04:39
I can't reproduce the 'undefined reference' issue with the code at head, so closing this.

**Closed by hyperrealm** 2017-10-17 04:39 UTC
Labels: build issue
