### ISSUE TITLE
Building libconfig on Bionic - Locales trouble (Warning)

### ISSUE THREAD

**Issue by giellamo** [hyperrealm/libconfig#120] opened 2018-07-11 10:47 UTC
I'm building master ( 04a3674f8fa3f009444c8173259a3ea57ef6c35d ) using CMAKE on bionic and have issues in compiling with the locale related functions.

> [0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/giellamo/projects/external/libconfig/build
[6/37] Building C object lib/CMakeFiles/libconfig.dir/libconfig.c.o
../lib/libconfig.c: In function ‘__config_locale_override’:
../lib/libconfig.c:99:2: warning: #warning "No way to modify calling thread's locale!" [-Wcpp]
 #warning "No way to modify calling thread's locale!"
  ^~~~~~~
../lib/libconfig.c: In function ‘__config_locale_restore’:
../lib/libconfig.c:120:2: warning: #warning "No way to modify calling thread's locale!" [-Wcpp]
 #warning "No way to modify calling thread's locale!"
  ^~~~~~~
[18/37] Building C object lib/CMakeFiles/libconfig++.dir/libconfig.c.o
../lib/libconfig.c: In function ‘__config_locale_override’:
../lib/libconfig.c:99:2: warning: #warning "No way to modify calling thread's locale!" [-Wcpp]
 #warning "No way to modify calling thread's locale!"
  ^~~~~~~
../lib/libconfig.c: In function ‘__config_locale_restore’:
../lib/libconfig.c:120:2: warning: #warning "No way to modify calling thread's locale!" [-Wcpp]
 #warning "No way to modify calling thread's locale!"
  ^~~~~~~
[37/37] Linking CXX executable out/c++_example2

It probably boils down to 
`
#elif ((defined HAVE_USELOCALE) && (defined HAVE_FREELOCALE))`

Any clue ?

**Comment by hyperrealm** [comment] 2018-07-12 00:53
Bionic doesn't have those per-thread locale functions, so on that platform your code has to make sure to set the "C" locale before calling into libconfig.

**Comment by giellamo** [comment] 2018-07-12 06:46
Just a small observation. With Bionic I'm referring to ubuntu 18.04 not the android libc...

**Comment by hyperrealm** [comment] 2018-10-10 03:05
I am on LinuxMint 18.1 (which I guess is Ubuntu 16.04?) and do not have that problem, so perhaps the newer Ubuntu removed those locale functions, or moved them to a different library such that the autoconf checks are no longer finding them correctly. Check the output of the 'configure' script to see what result it reports for those checks.

**Comment by BenjaminBeichler** [comment] 2018-11-09 17:00
I faced the same under Manjaro. But from my understanding this is caused by the basic cmake descriptions, which neither include the steps from autotools, nor implement them via their cmake pendents. My current quick fix is to add the following to lib/CMakeLists.txt


```
check_symbol_exists(uselocale "locale.h" HAVE_USELOCALE)
check_symbol_exists(newlocale "locale.h" HAVE_NEWLOCALE)
check_symbol_exists(freelocale "locale.h" HAVE_FREELOCALE)

if(HAVE_USELOCALE)
target_compile_definitions(${libname}
    PRIVATE "HAVE_USELOCALE")
endif()

if(HAVE_NEWLOCALE)
target_compile_definitions(${libname}
    PRIVATE "HAVE_NEWLOCALE")
endif()

if(HAVE_FREELOCALE)
target_compile_definitions(${libname}
    PRIVATE "HAVE_FREELOCALE")
endif()
```

But there are a lot more definitions set by Autotools, which currently do not let complain the compilation. A good example for better autoconf replacement is e.g. https://github.com/json-c/json-c/commit/f2e991a3419ee4078e8915e840b1a0d9003b349e

**Comment by hyperrealm** [comment] 2022-11-22 20:17
Closing as we merged all the fixes.

**Closed by hyperrealm** 2022-11-22 20:17 UTC
Labels: build issue
