### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by ponzipoh** [hyperrealm/libconfig#34] opened 2015-11-22 07:24 UTC
From the library website, I've found [this config file example](http://www.hyperrealm.com/libconfig/test.cfg.txt).
I'd like to know what kind of file format is that, if it's standardized or if it's a format you've just come up with for use in libconfig.

**Comment by jltallon** [comment] 2015-11-23 13:56
It's a custom *syntax* created by Mark Lindner.
The configuration file's format is to be defined by the library's user / application writer (i.e. YOU)

**Comment by hyperrealm** [comment] 2015-11-23 18:02
Hi, yes, the syntax was designed specifically for libconfig. My goal was to make it more-or-less C-like since the intended audience was (originally) C/C++ developers.

It's very similar to JSON, but not exactly.

**Comment by ponzipoh** [comment] 2015-11-23 18:13
@hyperrealm I love the idea of keeping the syntax as simple as possible, by means of removing all unnecessary characters (for example groups' brackets).
This way the config file can be edited both by libconfig and by hand, like for example when I edit simple ini files. The less cluttered it is, the better!

**Comment by hyperrealm** [comment] 2015-11-23 18:16
Without the grouping braces, how would you indicate the structure? Personally I'm not a fan of using whitespace indentation for that purpose, because then you can'd do things like:

origin: { x: 10, y : 20 }

**Comment by ponzipoh** [comment] 2015-11-23 19:41
What about lists and arrays instead? You could remove [] brackets, and only keep (). This would indicate a tuple, and the type (list or array) will be implicit.

**Comment by ponzipoh** [comment] 2015-11-23 21:55
Also, you could add on option to remove **:** and **=**. They are not necessary, especially before a **{**. For example

`origin { x: 10, y : 20 }`

**Comment by jltallon** [comment] 2015-11-24 12:07
On 11/23/2015 08:41 PM, ponzipoh wrote:
>
> What about lists and arrays instead? You could remove [] brackets, and 
> only keep (). This would indicate a tuple, and the type (list or 
> array) will be implicit.
>

You just gave the reason: "tuple" is different from "array"

**Comment by jltallon** [comment] 2015-11-24 12:09
On 11/23/2015 10:55 PM, ponzipoh wrote:
>
> Also, you could add on option to remove *:* and *=*. They are not 
> necessary, especially before a *{*. For example
>
> |origin { x: 10, y : 20 }|
>
>
I guess it'd create conflicts in the scanner and/or complicate the parser.
Haven't tested it, though .... Mark, could you share some insights on this?

**Comment by hyperrealm** [comment] 2015-12-23 03:32
It's probably doable; I don't think it would result in any grammar ambiguity but I don't know for sure unless I tried it. Doesn't seem worth the effort though; is having to enter that character really that big of a nuisance?

**Comment by hyperrealm** [comment] 2017-10-16 05:56
I'm not in favor of making these changes. Closing.

**Closed by hyperrealm** 2017-10-16 05:56 UTC
Labels: enhancement
